name: Kotlin Lint

on:
  pull_request:
    paths:
      - "kotlin/**"
      - "openapi.json"
      - '.github/workflows/kotlin-lint.yml'

jobs:
  kotlin:
    name: Kotlin Lint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Regen openapi libs
        run: |
          yarn
          ./regen_openapi.sh

      - name: Build
        run: |
          cd kotlin
          ./gradlew build -x test
